/**
 * @Author: Loïc Boiteux
 * @Date:   2023-04-03 12:54:43
 * @Last Modified by:   Loïc Boiteux
 * @Last Modified time: 2023-04-03 14:14:06
 */

import { SlashCommandBuilder, ChannelType, TextChannel, EmbedBuilder, ColorResolvable } from "discord.js"
import { readdirSync } from "fs";
import { join } from "path";
import { SlashCommand } from "../types/Commands";
import { letterCapitalize } from "../tools/stringTools"


const command: SlashCommand = {
    data: new SlashCommandBuilder()
        .setName("help")
        .setDescription("Need some help?"),
    execute: interaction => {


        // Embed du menu d'aide
        const helpEmbed = new EmbedBuilder()
            .setColor(0x990000)
            .setTitle('Help Menu')
            // .setAuthor({ name: interaction., iconURL: 'https://i.imgur.com/AfFp7pu.png', url: 'https://discord.js.org' })
            .setDescription('Need a little help?')
            .addFields({ name: '\u200B', value: '\u200B' })
            .setTimestamp()
            .setFooter({
                text: `Generated by ${interaction.client.user.username}`, iconURL: <string>interaction.client.user.avatarURL()
            });


        let slashCommandsDir = join(__dirname, "../slashCommands");
        let commandsDir = join(__dirname, "../commands");

        // Chargement des commandes Slash
        readdirSync(slashCommandsDir).forEach(file => {
            if (!file.endsWith(".ts")) return;
            let command: SlashCommand = require(`${slashCommandsDir}/${file}`).default;
            helpEmbed.addFields({ name: `/${letterCapitalize(command.data.name)}`, value: command.data.description })
        });

        interaction.reply({ embeds: [helpEmbed], ephemeral: true });
    }
}

export default command;