/**
 * @Author: Loïc Boiteux
 * @Date:   2023-04-11 09:40:32
 * @Last Modified by:   Loïc Boiteux
 * @Last Modified time: 2023-04-11 20:42:42
 */

import { SlashCommandBuilder, ChannelType, TextChannel, EmbedBuilder } from "discord.js"
import { SlashCommand } from "../types/Commands";

const fetch = require('node-fetch');

const command: SlashCommand = {
    data: new SlashCommandBuilder()
        .setName("reddit")
        .setDescription("Sends back posts from the provided subreddit.")
        .addStringOption(option =>
            option.setName('subreddit')
                .setDescription('The message to send.')
                .setRequired(true))
    // .addIntegerOption(option =>
    //     option.setName('amount')
    //     .setDescription('Amount of posts to send back')
    //     .setMaxValue(5))
    ,
    execute: async interaction => {
        const subreddit = <string>interaction.options.get("subreddit")?.value;

        let type = "";
        let titre = "";
        let auteur = "";
        let contenu = "";
        let image = "";
        let lien = "";

        // Obtention du post
        await fetch(`https://www.reddit.com/r/${subreddit}/new.json`)
            .then(async response => await response.json())
            .then(async response => {
                try {
                    let post = await response.data.children[2];
                                        
                    // Initialisation des attributs 
                    titre = post.data.title;
                    type = post.data.post_hint;
                    auteur = post.data.author;
                    lien = post.data.permalink;
                    contenu = post.data.selftext;
                    image = post.data.url_overridden_by_dest;
                    
                    if (post.data.is_video) {type = "image";}

                } catch (error) {
                    console.error(error);
                    interaction.reply("Something went wrong.");
                    return;
                }
            });

        
        // Embed du post
        const redditEmbed = new EmbedBuilder()
            .setColor(0x990000)
            .setTitle(titre)
            .setAuthor({ name: `From r/${subreddit}`, iconURL: 'https://www.iconpacks.net/icons/2/free-reddit-logo-icon-2436-thumb.png', url: `https://www.reddit.com/${lien}` })
            .setDescription(`By ${auteur}`)          
            .setTimestamp()
            .setFooter({
                text: `Generated by ${interaction.client.user.username}`, iconURL: <string>interaction.client.user.avatarURL()
            });

            // Ajout d'un champ selon le type du post
            if (type == "image") {
                redditEmbed.setImage(image)
            } else if (contenu ) {
                redditEmbed.addFields({ name: '\u200B', value: contenu })
            }
            
            // Envoi du post
            interaction.reply({ embeds: [redditEmbed], ephemeral: false });
    }
}

export default command;