/**
 * @Author: Loïc Boiteux
 * @Date:   2023-04-11 09:40:32
 * @Last Modified by:   Loïc Boiteux
 * @Last Modified time: 2023-04-11 14:44:10
 */

import { SlashCommandBuilder, ChannelType, TextChannel, EmbedBuilder } from "discord.js"
import { SlashCommand } from "../types/Commands";

const fetch = require('node-fetch');

const command: SlashCommand = {
    data: new SlashCommandBuilder()
        .setName("reddit")
        .setDescription("Sends back posts from the provided subreddit.")
        .addStringOption(option =>
            option.setName('subreddit')
                .setDescription('The message to send.')
                .setRequired(true))
    // .addIntegerOption(option =>
    //     option.setName('amount')
    //     .setDescription('Amount of posts to send back')
    //     .setMaxValue(5))
    ,
    execute: async interaction => {
        const subreddit = <string>interaction.options.get("subreddit")?.value;


        let titre = "";
        let auteur = "";
        let aa = "";
        let a = "";

        await fetch(`https://www.reddit.com/r/${subreddit}/new.json`)
            .then(async response => await response.json())
            .then(async data => {
                try {
                    await interaction.reply("Check your console, dad :3");
                    
                    let post = data.children[0];
                    
                    titre = post;
                    
                } catch (error) {
                    interaction.reply("Something fucked up");
                }
            });

        
        
        // // Embed du post
        // const redditEmbed = new EmbedBuilder()
        //     .setColor(0x990000)
        //     .setTitle('REDDIT')
        //     .setAuthor({ name: "interaction", iconURL: 'https://i.imgur.com/AfFp7pu.png', url: 'https://discord.js.org' })
        //     .setDescription('Need a little help?')
        //     .addFields({ name: '\u200B', value: '\u200B' })
        //     .setTimestamp()
        //     .setFooter({
        //         text: `Generated by ${interaction.client.user.username}`, iconURL: <string>interaction.client.user.avatarURL()
        //     });
    }
}

export default command;